version: "3.8"
services:
  pg-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intermedium
  api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - pg-database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pg-database:5432/intermedium
      - PORT=8000